server:
  port: 9407
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
    password: DEV4_07
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: DEV4_07
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

serverInfo:
  upload_path: C:\images\profile
  base_url: http:192.168.219.105/profile/