CREATE USER DEV4_07 IDENTIFIED BY DEV4_07;
GRANT CONNECT, RESOURCE, DBA TO DEV4_07;
GRANT ALTER SESSION TO DEV4_07;
CONN DEV4_07/DEV4_07;

-- CREATE TABLE MEMBER(
--     IDX NUMBER NOT NULL PRIMARY KEY, <- 시퀀스를 이용하여 값을 자동부여 (시퀀스 명 : IDX_SEQ)
--     ID VARCHAR2(10) NOT NULL UNIQUE,
--     PASSWORD VARCHAR2(15) NOT NULL,
--     NAME VARCHAR2(25) NOT NULL,
--     EMAIL VARCHAR2(26) NOT NULL,
--     PHONENUMBER VARCHAR(11) NOT NULL,
--     REGDATE VARCHAR2(11) NOT NULL,
--     PATH VARCHAR2(500)
-- );

-- CREATE TABLE ARTICLE(
--     NO NUMBER NOT NULL PRIMARY KEY, <- 시퀀스를 이용하여 값을 자동부여 (시퀀스 명 : ARTICLE_NO_SEQ)
--     TITLE VARCHAR2(100) NOT NULL,
--     WRITERID VARCHAR2(10) NOT NULL,
--     WRITERNAME VARCHAR2(25) NOT NULL,
--     CONTENT CLOB NOT NULL,
--     REGDATE VARCHAR2(11) NOT NULL,
--     READCNT NUMBER DEFAULT 0 NOT NULL,
-- )